// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_get_a_sniper = "CgkIm6Xsx9oYEAIQCQ"; // <GPGSID>
        public const string achievement_get_a_scientist = "CgkIm6Xsx9oYEAIQBg"; // <GPGSID>
        public const string achievement_get_a_defender = "CgkIm6Xsx9oYEAIQBw"; // <GPGSID>
        public const string achievement_get_a_engineer = "CgkIm6Xsx9oYEAIQCA"; // <GPGSID>
        public const string leaderboard_scoretest = "CgkIm6Xsx9oYEAIQCw"; // <GPGSID>
        public const string achievement_get_a_trader = "CgkIm6Xsx9oYEAIQDA"; // <GPGSID>

}

